---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multicluster-sso-controller
  namespace: open-cluster-management
---
apiVersion: v1
kind: Pod
metadata:
  name: multicluster-sso-controller
  namespace: open-cluster-management
spec:
  containers:
  - name: shell-operator
    image: quay.io/haoliu/multicluster-sso-controller:latest
    imagePullPolicy: Always
  serviceAccountName: multicluster-sso-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-sso-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: multicluster-sso-controller
  namespace: open-cluster-management
